### ISSUE TITLE
Erroneous sorting

### ISSUE THREAD

**Issue by Gitoffthelawn** [ariacorrente/simple-sort-bookmarks#7] opened 2016-05-12 02:25 UTC
The sorting of all subfolders works well, but the top level folder (which I don't want to be sorted anyways) has erroneous sorting.

Here's how it sorted it:

>
D-M
Separator
N-Z
Multiple Separators
A-C

Tested on FF 46.0.1

**Comment by Gitoffthelawn** [comment] 2016-05-12 02:32
Interesting.  After restarting Firefox, they sorted A-Z, but the Separators are in inappropriate positions, with three of them clumped together at the bottom.

**Comment by ariacorrente** [comment] 2016-05-17 20:42
I don't have an answer for the first temporary problem but I’ll keep an eye open on the root folder.

The separator are in inappropriate position because they are not respected when sorting. When I developed the addon I assumed that if an user needs the bookmarks sorted automatically then he wont need the separator because its useless to separate a sorted list.

Despite my initials assumptions you are the second user asking for this feature. Now its the most requested feature with the total of... let me check the statistics... yes, with a total of 2 users :). Maybe its time I look to this issue more seriously.

I close this issue as duplicate of #1 . If the problem in the first post happens again please open a new issue, thanks.

**Closed by ariacorrente** 2016-05-17 20:42 UTC

**Comment by Gitoffthelawn** [comment] 2016-05-17 20:49
Thanks!  And thanks for your sense of humor.  My first smile today.  :-)
